# Generated by Django 2.1.2 on 2018-10-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('run', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
                ('telefono', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('tipovivienda', models.CharField(choices=[('Patio grande', 'Patio grande'), ('Patio pequeño', 'Patio pequeño'), ('Casa sin patio', 'Casa sin patio'), ('Departamento', 'Departamento')], max_length=10)),
                ('mensaje', models.TextField(max_length=50)),
            ],
        ),
    ]
