# Generated by Django 2.1.2 on 2018-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('fecNac', models.DateField()),
                ('sexo', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], max_length=25)),
                ('tamaño', models.CharField(choices=[('p', 'Pequeño'), ('m', 'Mediano'), ('g', 'Grande')], max_length=25)),
            ],
        ),
    ]
