# Generated by Django 2.1.2 on 2018-10-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_imagen1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen1',
            field=models.ImageField(null=True, upload_to='albums/images/'),
        ),
    ]
