# Generated by Django 2.1.2 on 2018-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_auto_20181025_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('r', 'Rescatado'), ('d', 'Disponible'), ('a', 'Adoptado')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
